#!/bin/bash

# [Gedit Tool]
# Comment=4-select-test
# Input=nothing
# Applicability=all
# Shortcut=<Shift>F4
# Output=output-panel

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

TESTS=`echo cat "/GeditPyDevProject/tests/test/text()" | xmllint --shell gdp.xml | sed -e '/ --*/d; $d;'`
TEST=`zenity --title="Run doc tests" --list --text="Choose a file matching pattern or create a new one" --editable --column="Regex Pattern" $TESTS`

if [ -z "$TEST"  -o $? = 1 ]
then
	exit
fi

if [ "$TERM"  = "NEW" ]
then
	echo "Bad term; you pressed the enter key while you were adding the new term."
	exit
fi

NEW_TESTS=`echo -e "${TESTS}\n${TEST}" | sort -u | sed -e 's,\(.*\),<test>\1</test>,'`
START=`sed -e '1,/<tests>/!d;' gdp.xml`
END=`sed -e '/<.tests>/,$!d;' gdp.xml`
echo $START $NEW_TESTS $END | xmllint --format - > gdp.xml

echo Running tests that match $TEST
./test.py -vv --test="$TEST"












