#!/bin/bash

# [Gedit Tool]
# Comment=4-test
# Input=nothing
# Shortcut=F4
# Applicability=all
# Output=output-panel

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

IS_TEST=`echo $GEDIT_CURRENT_DOCUMENT_NAME | grep -c '\([.]txt\|[.]doctest\)'`
if [ $IS_TEST -ne 0  ]
then
	TEST="$GEDIT_CURRENT_DOCUMENT_NAME"
else
	TEST=`echo $GEDIT_CURRENT_DOCUMENT_NAME | sed  's/[.].*//'`
fi

IS_SEQ_TEST=`echo $TEST | grep -c '^[0-9][0-9]-'`
if [ $IS_SEQ_TEST -ne 0 ]
then
	TEST=`basename $GEDIT_CURRENT_DOCUMENT_DIR `
fi

LAYER=''
IS_PAGETEST=`echo $GEDIT_CURRENT_DOCUMENT_DIR| grep -c -E 'pagetest|stories'`
if [ $IS_PAGETEST -ne 0  ]
then
	LAYER='--layer=PageTest'
fi

if [ -f '_gdp.cfg' ]
then
    TESTS=`echo cat "/GeditPyDevProject/tests/test/text()" | xmllint --shell _gdp.cfg | sed -e '/ --*/d; $d;'`
NEW_TESTS=`echo -e "${TESTS}\n${TEST}" | sort -u | sed -e 's,\(.*\),<test>\1</test>,'`
    START=`sed -e '1,/<tests>/!d;' _gdp.cfg`
    END=`sed -e '/<.tests>/,$!d;' _gdp.cfg`
    echo $START $NEW_TESTS $END | xmllint --format - > _gdp.cfg
fi

export PYTHONPATH=lib:$PYTHONPATH:/usr/bin:/usr/lib/gedit-2/plugins
echo Running tests that match $TEST
./bin/test -vv $LAYER --test="(doc|test|stories).*$TEST"





























