#!/bin/bash

# [Gedit Tool]
# Comment=5 bzr diff
# Name=5 bzr diff
# Shortcut=F5
# Applicability=all
# Input=nothing
# Output=output-panel

BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

bzr diff > _diff.diff
gedit _diff.diff









