#!/bin/bash

# [Gedit Tool]
# Comment=Bazaar status
# Input=nothing
# Name=bzr status
# Applicability=all
# Output=output-panel

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

#bzr st | zenity --text-info --title="$BRANCH status" &
bzr gst &










