#!/bin/bash

# [Gedit Tool]
# Comment=bzr-annotate
# Name=bzr gannonate
# Input=nothing
# Applicability=all
# Output=output-panel

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

bzr gannotate  $GEDIT_CURRENT_DOCUMENT_PATH &


