#!/bin/bash

# [Gedit Tool]
# Comment=bzr-commit
# Name=bzr commit
# Shortcut=<Control><Alt><Super>c
# Applicability=all
# Output=output-panel
# Input=nothing

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

# Was Gedit started from a terminal? Is there a controlling tty?
this_tty=`tty`
have_tty=$?

if [ $have_tty = '1' ]
then
	gnome-terminal -x bzr gci &
else
	bzr gci &
fi







































