#!/bin/bash

# [Gedit Tool]
# Comment=Bazaar push
# Input=nothing
# Name=bzr push
# Applicability=all
# Output=output-panel

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH
cd $BRANCH

bzr gpush &










