#!/bin/bash

# [Gedit Tool]
# Comment=_find-in-files
# Name=Find in project files
# Shortcut=<Shift><Control>f
# Applicability=all
# Output=output-panel
# Input=nothing

PWD=`pwd`
BRANCH=`bzr root`
if [ -n "$BRANCH" ]
then
    echo Branch is at $BRANCH
    cd $BRANCH
else
    if [ -n "$GEDIT_CURRENT_DOCUMENT_DIR" ]
    then
        echo document is at "$GEDIT_CURRENT_DOCUMENT_DIR"
        cd "$GEDIT_CURRENT_DOCUMENT_DIR"
    fi
fi

# Set newlines as the only valid separator.
IFS="
"

TERMS='_NEW_'
if [ -f 'gdp.xml' ]
then
    TERMS=`echo cat "/GeditPyDevProject/searches/search/text()" | xmllint --shell gdp.xml | sed -e '/ --*/d; $d; s/\&gt;/>/; s/\&lt;/</;'`
fi

TERM=`zenity --class=WINDOW_POPUP --title="Find in files" --list --text="Choose a search pattern or create a new one" --editable --column="Regex Pattern" $TERMS`

if [ -z "$TERM"  -o $? = 1 ]
then
	exit
fi

if [ "$TERM"  = "NEW" ]
then
	echo "Bad term; you pressed the enter key while you were adding the new term."
	exit
fi

if [ -f 'gdp.xml' ]
then
    NEW_SEARCHES=`echo -E "${TERMS}${IFS}${TERM}"  | sort -u | sed -e 's,>,\&gt;,g; s,<,\&lt;,g; s,\(.*\),<search>\1</search>,'`
    START=`sed -e '1,/<searches>/!d;' gdp.xml`
    END=`sed -e '/<.searches>/,$!d;' gdp.xml`

    echo -E $START $NEW_SEARCHES $END | xmllint --format - > gdp.xml
fi

echo "searching `pwd`"

${HOME}/.gnome2/gedit/tool/find.py ./ '\.(py|txt|conf|zcml|pt|js|tac|xml|html|Makefile|doctest)$' "$TERM"










