#!/bin/bash

# [Gedit Tool]
# Comment=Reformat a doctest
# Input=nothing
# Name=Format doctest
# Applicability=all
# Output=output-panel

${HOME}/.gnome2/gedit/tool/formatdoctest.py -f $GEDIT_CURRENT_DOCUMENT_PATH

