#!/bin/bash

# [Gedit Tool]
# Comment=Syntax help
# Name=Help
# Shortcut=<Alt>F1
# Applicability=all
# Output=output-panel
# Input=selection

read TERM

PWD=`pwd`
BRANCH=`bzr root`
echo Branch is at $BRANCH

PYTHONPATH="${BRANCH}:$PYTHONPATH"

if [ -d "${BRANCH}/lib" ]
then
	PYTHONPATH="${BRANCH}/lib:$PYTHONPATH"
fi 

export PYTHONPATH=$PYTHONPATH

FULL_TERM=`pydoc2.4 -k $TERM | zenity --title="Help topics" --list --text="Choose a class to see its documentation" --editable --column="Class"`

if [ -z "$FULL_TERM"  -o $? = 1 ]
then
	exit
fi

FULL_TERM=`echo $FULL_TERM | sed -e 's/[ \t\n]//g;'`

pydoc2.4 $FULL_TERM

















