#!/bin/sh

# [Gedit Tool]
# Comment=open-terminal-here
# Input=nothing
# Applicability=all
# Output=output-panel

#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
gnome-terminal --working-directory=$GEDIT_CURRENT_DOCUMENT_DIR &
