#!/bin/sh

# [Gedit Tool]
# Comment=run-command
# Input=nothing
# Applicability=all
# Output=output-panel

#TODO: use "gconftool-2 -g /desktop/gnome/applications/terminal/exec"
#exec `zenity --entry --title="Run command - gedit" --text="Command to run"`

this_tty=`tty`
have_tty=$?

echo $have_tty


